-- WISE 홈페이지용 Supabase 초기 설정
-- Supabase SQL Editor에서 전체 실행

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  type text,
  video_url text,
  thumbnail_url text,
  storage_path text,
  featured boolean default false,
  sort_order integer default 0,
  created_at timestamptz default now()
);

alter table public.projects enable row level security;

drop policy if exists "Public can read projects" on public.projects;
create policy "Public can read projects"
on public.projects for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated can insert projects" on public.projects;
create policy "Authenticated can insert projects"
on public.projects for insert
to authenticated
with check (true);

drop policy if exists "Authenticated can update projects" on public.projects;
create policy "Authenticated can update projects"
on public.projects for update
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated can delete projects" on public.projects;
create policy "Authenticated can delete projects"
on public.projects for delete
to authenticated
using (true);

insert into storage.buckets (id, name, public)
values ('thumbnails', 'thumbnails', true)
on conflict (id) do update set public = true;

drop policy if exists "Public can view thumbnails" on storage.objects;
create policy "Public can view thumbnails"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'thumbnails');

drop policy if exists "Authenticated can upload thumbnails" on storage.objects;
create policy "Authenticated can upload thumbnails"
on storage.objects for insert
to authenticated
with check (bucket_id = 'thumbnails');

drop policy if exists "Authenticated can delete thumbnails" on storage.objects;
create policy "Authenticated can delete thumbnails"
on storage.objects for delete
to authenticated
using (bucket_id = 'thumbnails');
